### ISSUE TITLE
SampleEndLoop error comes up

### ISSUE THREAD

**Issue by nathanblanchard12** [chipweinberger/dart_melty_soundfont#9] opened 2022-04-25 12:57 UTC
I am getting a flutter: 'sampleEndLoop' is out of range. 'STRING error. My code 

static byteToPlayer() async {
    try{
      // Create the synthesizer.
      ByteData bytes = await rootBundle.load(defaultURL);

      Synthesizer synth = Synthesizer.loadByteData(bytes);

      // Turn on some notes
      synth.noteOn(channel: 0, key: noteToPlay, velocity: 120);

      // Render the waveform (3 seconds)
      ArrayInt16 buf16 = ArrayInt16.zeros(numShorts: 44100 * 3);

      synth.renderMonoInt16(buf16);

      return {"bytes" : buf16.bytes.buffer.asUint8List(), "isSuccessful": true};
    }catch(e){
      print('byteToPlayer');
      print(e);
      return {"bytes" : 0, "isSuccessful": false};
    }
  }

**Comment by chipweinberger** [comment] 2022-04-26 20:20
please share a copy of your SF2 file.

**Comment by nathanblanchard12** [comment] 2022-04-26 21:29
[Brass.sf2.zip](https://github.com/chipweinberger/DartMeltySoundFont/files/8566996/Brass.sf2.zip)

**Comment by chipweinberger** [comment] 2022-04-27 02:25
@sinshu, any chance you want to try this file in your C# version?

**Comment by sinshu** [comment] 2022-04-27 02:46
The C# version works with the following code.
The output waveform seems OK as well.

```cs
// Create the synthesizer.
var sampleRate = 44100;
var synthesizer = new Synthesizer("Brass.sf2", sampleRate);

// Play some notes (middle C, E, G).
synthesizer.NoteOn(0, 60, 100);
synthesizer.NoteOn(0, 64, 100);
synthesizer.NoteOn(0, 67, 100);

// The output buffer (3 seconds).
var left = new float[3 * sampleRate];
var right = new float[3 * sampleRate];

// Render the waveform.
synthesizer.Render(left, right);
```

**Comment by chipweinberger** [comment] 2022-04-27 02:49
Thanks for trying. oh no! a bug in my port! =(

**Comment by chipweinberger** [comment] 2022-04-27 02:59
@nathanblanchard12, you may have to debug this further yourself. I wont be able to look at it for a few weeks.

**Comment by nathanblanchard12** [comment] 2022-04-30 04:57
Ok let me know. :)

**Comment by chipweinberger** [comment] 2022-04-30 10:19
I'm not reproducing this issue:

I added this print statement:

```
        print("endloop: ${region.sampleEndLoop()} sampleCount: $sampleCount");
        
        if (!(0 < region.sampleEndLoop() &&
            region.sampleEndLoop() <= sampleCount)) {
          throw "'sampleEndLoop' is out of range. '${region.sample.name}'.'${instrument.name}'.";
        }
```

And I get these results:

```
flutter: endloop: 40250 sampleCount: 112664
flutter: endloop: 56319 sampleCount: 112664
flutter: endloop: 40250 sampleCount: 112664
flutter: endloop: 56319 sampleCount: 112664
flutter: endloop: 40250 sampleCount: 112664
flutter: endloop: 56319 sampleCount: 112664
flutter: endloop: 40250 sampleCount: 112664
flutter: endloop: 56319 sampleCount: 112664
flutter: endloop: 40250 sampleCount: 112664
flutter: endloop: 56319 sampleCount: 112664
flutter: endloop: 40250 sampleCount: 112664
flutter: endloop: 56319 sampleCount: 112664
flutter: endloop: 40250 sampleCount: 112664
flutter: endloop: 40250 sampleCount: 112664
flutter: endloop: 40250 sampleCount: 112664
flutter: endloop: 56319 sampleCount: 112664
flutter: endloop: 40250 sampleCount: 112664
flutter: endloop: 56319 sampleCount: 112664
flutter: endloop: 40250 sampleCount: 112664
flutter: endloop: 56319 sampleCount: 112664
flutter: endloop: 40250 sampleCount: 112664
flutter: endloop: 56319 sampleCount: 112664
flutter: endloop: 40250 sampleCount: 112664
flutter: endloop: 56319 sampleCount: 112664
flutter: endloop: 40250 sampleCount: 112664
flutter: endloop: 56319 sampleCount: 112664
```

**Comment by chipweinberger** [comment] 2022-04-30 10:23
Interestingly, it still does not work though. I get an error here.

<img width="845" alt="Screen Shot 2022-04-30 at 5 20 23 AM" src="https://user-images.githubusercontent.com/1863934/166101660-8bc679e2-74b9-431e-a68d-4918afb489b0.png">

I take it you are on web? I know dart handles numbers differently on web. I don't have code that loads SF2 files on web yet (did you write your own?).

**Comment by chipweinberger** [comment] 2022-04-30 11:06
So debugging the above error a bit, I see a crazy value for fineTine, which is causing us to do crazy pitchRatios and calculate bad array bounds. 

gs.[GeneratorType.fineTune] = 65497

Which is out of range since fine tuning should be [-8192,8191]

@sinshu, I dont see how your code deals with signed/vs unsigned for GeneratorType.fineTune. **Edit:** It looks liked you read from the file as `ushort`, but implicitly convert to `short` in `InstrumentRegion.cs`. I'm not sure how C# handles implicit conversions. 

Dart does not have shorts (only ints).

I wrote this code to work around the int only limitation, but I think it's causing problems because I dont handle signed/unsigned?

```
int castToShort(int v) {
  return v & 0xFFFF;
}
```


@sinshu, does your c# version actually render correctly?

```
class Generator
{
    final GeneratorType type;
    final int value; // ushort

    Generator(this.type, this.value);

    factory Generator.fromReader(BinaryReader reader)
    {
        GeneratorType type = generatorTypeFromInt(reader.readUInt16());
        int value = reader.readUInt16(); // I later call castToShort on this

        return Generator(type, value);
    }
```

**Comment by chipweinberger** [comment] 2022-04-30 11:31
Think i just need to do this:

```
int castToByte(int v) {
  int m = v & 0xFF;
  if (m >= 128){
    // handle two's compliment
    m = -128 + (m - 128);
  }
  return m;
}

int castToShort(int v) {
  int m = v & 0xFFFF;
  if (m >= 32768){
    // handle two's compliment
    m = -32768 + (m - 32768);
  }
  return m;
}
```

**Comment by sinshu** [comment] 2022-04-30 11:35
Most of the fine tuning values were -39 in the C# version.
Since the value 65497 = 65536 - 39, your fix above should work.

**Comment by chipweinberger** [comment] 2022-04-30 11:35
Yes that fixed it! Beautiful brass music!

**Comment by chipweinberger** [comment] 2022-04-30 11:51
Pushed the fix to pub.dev.

**Comment by chipweinberger** [comment] 2022-04-30 11:53
thanks @sinshu!

**Comment by chipweinberger** [comment] 2022-05-24 05:31
Brass.sf2.zip works for me with the above change, closing.

**Closed as completed by chipweinberger** 2022-05-24 05:31 UTC
